### ISSUE TITLE
Docker Image error 

### ISSUE THREAD

**Issue by mmihir82** [yzguy/netztp#12]
After the building the docker image. Try to run the docker image, got error
```
[+] Running 0/1
 ⠿ Container netztp-master-backend-1  Starting                                                                                                                                 0.5s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": cannot run executable found relative to current directory: unknown
```
Have seen this error?

**Comment by yzguy** [comment]
Not sure, I haven't touched this in a bit. Just updated the python version to 3.11.3 and updated deps to latest.

I also put a more specific path to `gunicorn`, eg `venv/bin/gunicorn` vs just `gunicorn`. I deployed this new updated version at home and it works as expected fortunately.

I did experience the same error as you posted though surprisingly, even with the same image that I've had running for a long time
