### ISSUE TITLE
Cumulus Devices

### ISSUE THREAD

**Issue by mmihir82** [yzguy/netztp#9]
Does the netZTP support cumulus OS?
So is there demo, can be spin up?

**Comment by yzguy** [comment]
@mmihir82 It does not actually, BUT I'm not against it as I have been using Cumulus devices recently. Something I can look into!

Reference for myself: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-56/Installation-Management/Zero-Touch-Provisioning-ZTP/

Realistically this project is more for me personally/learning, and as a reference for others.

**Comment by mmihir82** [comment]
totally make sense. I'm also building on the side to support multi-vendor ZTP support. Which I came across your git. If you like, I have working version of Cumulus ZTP.

**Comment by yzguy** [comment]
@mmihir82 I "implemented" this, but very basically as the ZTP process for Cumulus is trivial. Just a DHCP option, tell it to hit NetZTP, and it gets fed back a script that is run.

The big part of the process would be contained inside that script

https://github.com/yzguy/netztp/commit/28e0fe8dfd1f9b623a27d1b00271a3a0541d0920
